// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blueBoxContainer': string;
  'container': string;
  'ideas': string;
  'img': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
